# Generated by Django 4.2.7 on 2023-11-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('car_type', models.CharField(max_length=255)),
                ('brief_description_of_the_car', models.CharField(max_length=255)),
                ('car_category', models.CharField(max_length=255)),
                ('no_of_seats', models.IntegerField(blank=True, default=1, null=True)),
                ('amount_per_day', models.FloatField(default=5000)),
            ],
        ),
    ]
