# Generated by Django 4.2.7 on 2023-11-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.URLField(default='https://res.cloudinary.com/dxrxrd21n/image/upload/f_auto,q_auto/ooybbpi6zlzdllvuukuv'),
        ),
    ]
