# Generated by Django 4.2.7 on 2023-11-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='brief_description_of_the_car',
            field=models.TextField(max_length=1024),
        ),
    ]
