# Generated by Django 4.2.7 on 2023-11-24 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_car_car_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
