# Generated by Django 4.2.7 on 2023-11-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_car_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image_urls',
            field=models.URLField(default='https://res.cloudinary.com/dxrxrd21n/image/upload/f_auto,q_auto/ooybbpi6zlzdllvuukuv'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
