# Generated by Django 4.2.7 on 2023-11-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_car_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('phone_number', models.CharField(max_length=1024)),
                ('address', models.CharField(max_length=2555)),
                ('town_city', models.CharField(max_length=1025)),
                ('pickup_location', models.CharField(max_length=2555)),
                ('pickup_date', models.DateTimeField()),
                ('dropoff_location', models.CharField(max_length=2555)),
                ('dropoff_date', models.DateTimeField()),
                ('payment_amount', models.FloatField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('car_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.car')),
            ],
        ),
    ]
