# Generated by Django 4.2.7 on 2023-11-30 15:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_car_car_image_urls_alter_car_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='images'),
            preserve_default=False,
        ),
    ]
