# Generated by Django 4.2.7 on 2023-12-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_car_car_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('car_category', models.CharField(max_length=255)),
                ('vehicle_cleanliness', models.CharField(max_length=255)),
                ('pickup_and_dropoff', models.CharField(max_length=255)),
                ('staff_professionalism', models.CharField(max_length=3055)),
            ],
        ),
    ]
