# Generated by Django 4.2.7 on 2023-11-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='email_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
