# Generated by Django 4.2.7 on 2023-11-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_payments_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_ref',
            field=models.CharField(default='', max_length=255),
        ),
    ]
