# Generated by Django 4.2.7 on 2023-11-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_payments_payment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='dropoff_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pickup_date',
            field=models.DateField(),
        ),
    ]
