# Generated by Django 4.2.7 on 2023-11-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_payments_dropoff_date_payments_number_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
